# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieListTestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieListTestApp
	pod 'SDWebImage', '~> 4.0'
    pod 'ReachabilitySwift'

  target 'MovieListTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieListTestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
